{-# LANGUAGE NoImplicitPrelude #-}

module BNFC.Backend.SV.FuseSoC (fusesoc) where

import Prelude (String, (++), unlines)

import BNFC.Backend.SV.Config

fusesoc :: SVConfig -> String
fusesoc cfg =
  unlines
   [   "name: \"lib:interp:" ++ svName cfg ++ "\""
    ,  "description: \"interp lib\""
    ,  "filesets:"
    ,  "  pkg:"
    ,  "    files:"
    ,  ""
    ,  "      - " ++ svUpperName cfg ++ "Absyn.svh: {is_include_file: true}"
    ,  "      - " ++ svUpperName cfg ++ "Interp.svh: {is_include_file: true}"
    ,  "      - " ++ svUpperName cfg ++ "Lexer.svh: {is_include_file: true}"
    ,  "      - " ++ svUpperName cfg ++ "Printer.svh: {is_include_file: true}"
    ,  "      - bio.svh: {is_include_file: true}"
    ,  "      - " ++ svUpperName cfg ++ "Parser.svh: {is_include_file: true}"
    ,  "      - " ++ svUpperName cfg ++ "Absyn.sv: {is_include_file: true}"
    ,  "      - " ++ svUpperName cfg ++ "Interp.sv: {is_include_file: true}"
    ,  "      - " ++ svUpperName cfg ++ "Printer.sv: {is_include_file: true}"
    ,  ""
    ,  "      - " ++ svName cfg ++ "_pkg.sv"
    ,  "    file_type: systemVerilogSource"
    ,  ""
    ,  "  tb:"
    ,  "    files:"
    ,  "      - ../Test.sv"
    ,  "    file_type: systemVerilogSource"
    ,  ""
    ,  "targets:"
    ,  "  default: &default"
    ,  "    filesets:"
    ,  "      - pkg"
    ,  ""
    ,  "  sim: &sim"
    ,  "    <<: *default"
    ,  "    description: Simulate the design"
    ,  "    default_tool: modelsim"
    ,  "    filesets_append:"
    ,  "      - tb"
    ,  "    tools:"
    ,  "      vcs:"
    ,  "        vcs_options:"
    ,  "          - -g2012"
    ,  "      xsim:"
    ,  "        xelab_options:"
    ,  "          - \"--debug all\""
    ,  "      modelsim:"
    ,  "        vlog_options:"
    ,  "          - \"--debug all\""
    ,  ""
    ,  "  test:"
    ,  "    <<: *sim"
    ,  "    toplevel: test"
    ,  "    default_tool: vcs"
    ,  "    parameters:"
    ,  "      - input=test.w"
    ,  ""
    ,  "parameters:"
    ,  "  input:"
    ,  "    datatype: str"
    ,  "    paramtype: plusarg"
    ,  ""
   ]
